##
# @description Markdown lint
# @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
##

##
# @note Unordered list style
##
MD004:
  style: dash

##
# @note Ordered list item prefix
##
MD029:
  style: one
