##
# @description Linter
# @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
##
name: Linter

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main

jobs:
  lint:
    name   : Lint
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout
        id  : checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id  : setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache       : npm

      - name: Install dependencies
        id  : install
        run : npm ci

      - name: Lint source code
        id  : super-linter
        uses: super-linter/super-linter/slim@v5
        env :
          DEFAULT_BRANCH          : main
          TYPESCRIPT_DEFAULT_STYLE: prettier
          VALIDATE_JSCPD          : false
